"""empty message

Revision ID: 77579b7c986d
Revises: 25644d728c82
Create Date: 2022-04-25 18:53:45.529891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77579b7c986d'
down_revision = '25644d728c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'image_link')
    # ### end Alembic commands ###
